<a href="https://colab.research.google.com/github/mokhivibes/games/blob/main/30_Lesson_Recap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install opendatasets

Requirement already satisfied: opendatasets in /usr/local/lib/python3.12/dist-packages (0.1.22)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from opendatasets) (4.67.3)
Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (from opendatasets) (2.0.2)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from opendatasets) (8.4.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (6.4.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (1.19.4)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (0.1.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (26.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.32.4)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle->opendatasets) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle->opendatasets) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle->opendatasets) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle->opendatasets) (5.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle->opendatasets) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle->opendatasets) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle->opendatasets) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle->opendatasets) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle->opendatasets) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle->opendatasets) (2026.6.17)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle->opendatasets) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle->opendatasets) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle->opendatasets) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle->opendatasets) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle->opendatasets) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle->opendatasets) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle->opendatasets) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle->opendatasets) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle->opendatasets) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle->opendatasets) (4.10.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle->opendatasets) (4.16.0)

In [2]:
import opendatasets as od

In [3]:
od.download("https://www.kaggle.com/competitions/titanic/data")

Skipping, found downloaded files in "./titanic" (use force=True to force download)

In [4]:
import pandas as pd

In [5]:
data = pd.read_csv("/content/titanic/train.csv")

In [6]:
data.shape

(891, 12)

In [7]:
df = data.copy()

In [8]:
df['Cabin'].isnull().sum() / len(df) * 100

np.float64(77.10437710437711)

In [9]:
df.drop('Cabin', axis=1, inplace=True)

In [10]:
df['Embarked'].isnull().sum() / len(df) * 100

np.float64(0.22446689113355783)

In [11]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [12]:
df.dropna(subset='Embarked', inplace=True)

In [13]:
df['Embarked'].isnull().sum()

np.int64(0)

In [14]:
df['Age'].isnull().sum() / len(df) * 100

np.float64(19.910011248593925)

In [15]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [16]:
df['Age'].isnull().sum()

np.int64(0)

In [17]:
df.shape

(889, 11)

🧠 1-BOSQICH — FEATURE ENGINEERING

In [18]:
df['family_size'] = df['SibSp'] + df['Parch'] + 1

In [19]:
df['family_size'].describe()

count    889.000000
mean       1.906637
std        1.614703
min        1.000000
25%        1.000000
50%        1.000000
75%        2.000000
max       11.000000
Name: family_size, dtype: float64

In [20]:
df['family_size'].min()

1

In [21]:
df['family_size'].max()

11

In [22]:
df['family_size'].mean()

np.float64(1.9066366704161979)

In [23]:
#Nega hisoblashda yo‘lovchining o‘zini ham hisobga olish kerak?
#chunki oilaviy borganda yolovchini 1 qilib qoshib qoymasak oila azolari boldayu ozi qoshilmay qoladi, + agar bitta ozi bolsa ozini 1 qilib kethishimiz kerak

🔥 Task 2 — Is Alone

In [24]:
df['is_alone'] = df['family_size'] == 1

In [25]:
df['is_alone'].value_counts()

is_alone
True     535
False    354
Name: count, dtype: int64

🔥 Task 3 — Name'dan ma'lumot qazib ol

In [26]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 889, dtype: object

In [27]:
df['Title'] = df['Name'].str.extract(r'\s*, ([^\.]+)\.')
df['Title']

0        Mr
1       Mrs
2      Miss
3       Mrs
4        Mr
       ...
886     Rev
887    Miss
888    Miss
889      Mr
890      Mr
Name: Title, Length: 889, dtype: object

In [28]:
df['Title'].value_counts()

Title
Mr              517
Miss            181
Mrs             124
Master           40
Dr                7
Rev               6
Col               2
Mlle              2
Major             2
Ms                1
Mme               1
Don               1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64

🔥 Task 4 — Rare Titles

In [29]:
for value in df['Title'].value_counts().index:
  if df['Title'].value_counts()[value] <= 2:
    df['Title'] = df['Title'].replace(value, 'Rare')

In [30]:
df['Title'].value_counts()

Title
Mr        517
Miss      181
Mrs       124
Master     40
Rare       14
Dr          7
Rev         6
Name: count, dtype: int64

🔥 Task 5 — Fare Per Person

In [31]:
import numpy as np

df['fare_per_person'] = df['Fare'] / df['family_size']

df['fare_per_person'].describe()

count    889.000000
mean      19.781204
std       35.767862
min        0.000000
25%        7.250000
50%        8.158300
75%       22.525000
max      512.329200
Name: fare_per_person, dtype: float64

In [32]:
print(df['fare_per_person'].mean(),
df['fare_per_person'].min(),
df['fare_per_person'].max())

19.7812038523269 0.0 512.3292

In [33]:
df['fare_per_person'] = np.round(df['fare_per_person'], 2)

In [34]:
#Nega Fareni shunchaki modelga berishdan ko‘ra fare_per_person foydaliroq feature bo‘lishi mumkin?
#Chunki har bir odam nechchi puldan to'laganini aniqlashimiz va u kamroq yoki koproq tolaganiga qarab tirik qolishga tasiri bormi korishimiz ham mumkin\

🔥 Task 6 — Yana bitta mustaqil Feature

In [35]:
# df['age_group'] = pd.cut(df['Age'], bins=[0, 18, 60, 80], labels=['child','adult', 'senior'])


# df['age_group'].value_counts()

In [36]:
age_groups = []

for value in df['Age']:
  if value < 18:
    age_groups.append('child')
  elif value >= 18 and value < 60:
    age_groups.append('adult')
  else:
    age_groups.append('senior')

df['age_group'] = age_groups

In [37]:
df['age_group'].value_counts()

age_group
adult     751
child     113
senior     25
Name: count, dtype: int64

🔥 Task 7 — Name Length

In [38]:
length = []

for value in df['Name']:
  length.append(len(value))

In [39]:
df['length_name'] = length

In [40]:
df['length_name'].mean()

np.float64(26.95838020247469)

In [41]:
df['length_name'].max()

82

In [42]:
df['length_name'].min()

12

In [43]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked', 'family_size', 'is_alone',
       'Title', 'fare_per_person', 'age_group', 'length_name'],
      dtype='object')

In [44]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df['sex_encoded'] = le.fit_transform(df['Sex'])
df['is_alone_encoded'] = le.fit_transform(df['is_alone'])

In [45]:
df['sex_encoded']

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: sex_encoded, Length: 889, dtype: int64

In [46]:
embarked_dummies = pd.get_dummies(df['Embarked'], prefix='Embarked')
df = pd.concat([df, embarked_dummies], axis=1)

In [47]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked', 'family_size', 'is_alone',
       'Title', 'fare_per_person', 'age_group', 'length_name', 'sex_encoded',
       'is_alone_encoded', 'Embarked_C', 'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [48]:
age_group_dummies = pd.get_dummies(df['age_group'], prefix='age_group')
df = pd.concat([df, age_group_dummies], axis=1)

In [49]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked', 'family_size', 'is_alone',
       'Title', 'fare_per_person', 'age_group', 'length_name', 'sex_encoded',
       'is_alone_encoded', 'Embarked_C', 'Embarked_Q', 'Embarked_S',
       'age_group_adult', 'age_group_child', 'age_group_senior'],
      dtype='object')

In [50]:
title_dummies = pd.get_dummies(df['Title'], prefix='Title')
df = pd.concat([df, title_dummies], axis=1)

In [51]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked', 'family_size', 'is_alone',
       'Title', 'fare_per_person', 'age_group', 'length_name', 'sex_encoded',
       'is_alone_encoded', 'Embarked_C', 'Embarked_Q', 'Embarked_S',
       'age_group_adult', 'age_group_child', 'age_group_senior', 'Title_Dr',
       'Title_Master', 'Title_Miss', 'Title_Mr', 'Title_Mrs', 'Title_Rare',
       'Title_Rev'],
      dtype='object')

🔥 Task 8 — Sex

In [52]:
df.groupby('Pclass')['Survived'].mean()

Pclass
1    0.626168
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [ ]:
# | Ustun    | Kategoriya soni | Tartib bormi? | Qaysi encoding? |
# | -------- | --------------: | ------------- | --------------- |
# | Sex      |               2 | yoq             | labelencoding               |
# | Embarked |               3 | yoq             | one hot encoding               |
# | Title    |               5 | yoq             | one hot               |
# | Pclass   |               3 | ha             | kerakmas              |
# | is_alone |               2 | yoq             | label encoding               |

🔥 3-BOSQICH — SCALING

In [59]:
print(f"Min of Age:{df['Age'].min()},\nMean of Age: { df['Age'].mean()},\nMax of Age: {df['Age'].max()}")

Min of Age:0.42,
Mean of Age: 29.642092696629216,
Max of Age: 80.0

In [60]:
print(f"Min of Fare:{df['Fare'].min()},\nMean of Fare: { df['Fare'].mean()},\nMax of Fare: {df['Fare'].max()}")

Min of Fare:0.0,
Mean of Fare: 32.09668087739032,
Max of Fare: 512.3292

In [62]:
print(f"Min of Family size:{df['family_size'].min()},\nMean of Family size: { df['family_size'].mean()},\nMax of Family size: {df['family_size'].max()}")

Min of Family size:1,
Mean of Family size: 1.9066366704161979,
Max of Family size: 11

In [61]:
print(f"Min of fare_per_person:{df['fare_per_person'].min()},\nMean of fare_per_person: { df['fare_per_person'].mean()},\nMax of fare_per_person: {df['fare_per_person'].max()}")

Min of fare_per_person:0.0,
Mean of fare_per_person: 19.781214848143982,
Max of fare_per_person: 512.33

In [ ]:
#Nega ba'zi ML algoritmlarida scaling kerak bo‘lishi mumkin?
#Shu savolga ozing javob ber

🔥 Task 14 — Min-Max

In [66]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df['age_scaled'] = scaler.fit_transform(df[['Age']])

In [67]:
df['age_scaled'].describe()

count    889.000000
mean       0.367204
std        0.162960
min        0.000000
25%        0.271174
50%        0.367204
75%        0.434531
max        1.000000
Name: age_scaled, dtype: float64

In [77]:
df['family_size'].describe()

count    889.000000
mean       1.906637
std        1.614703
min        1.000000
25%        1.000000
50%        1.000000
75%        2.000000
max       11.000000
Name: family_size, dtype: float64

In [78]:
df['family_size_scaled'] = scaler.fit_transform(df[['family_size']])

In [79]:
df['family_size_scaled'].describe()

count    889.000000
mean       0.090664
std        0.161470
min        0.000000
25%        0.000000
50%        0.000000
75%        0.100000
max        1.000000
Name: family_size_scaled, dtype: float64

In [68]:
from sklearn.preprocessing import StandardScaler

scaler_s = StandardScaler()

df['Fare_scaled'] = scaler_s.fit_transform(df[['Fare']])

In [81]:
df['length_name'].describe()

count    889.000000
mean      26.958380
std        9.276257
min       12.000000
25%       20.000000
50%       25.000000
75%       30.000000
max       82.000000
Name: length_name, dtype: float64

In [82]:
df['length_name_std'] = scaler_s.fit_transform(df[['length_name']])

In [84]:
df['length_name_std'].describe()

count    8.890000e+02
mean     1.178909e-16
std      1.000563e+00
min     -1.613453e+00
25%     -7.505503e-01
50%     -2.112363e-01
75%      3.280776e-01
max      5.936942e+00
Name: length_name_std, dtype: float64

In [69]:
df['Fare_scaled'].describe()

count    8.890000e+02
mean     1.398706e-16
std      1.000563e+00
min     -6.462044e-01
25%     -4.872378e-01
50%     -3.551972e-01
75%     -2.207954e-02
max      9.668551e+00
Name: Fare_scaled, dtype: float64

In [70]:
df['fare_per_person_minmax'] = scaler.fit_transform(df[['fare_per_person']])

In [71]:
df['fare_per_person_std'] = scaler_s.fit_transform(df[['fare_per_person']])

In [73]:
print(f"Describe of fare_per_person_minmax: {df['fare_per_person_minmax'].describe()}\n")
print(f"Describe of fare_per_person_std: {df['fare_per_person_std'].describe()}")

Describe of fare_per_person_minmax: count    889.000000
mean       0.038610
std        0.069814
min        0.000000
25%        0.014151
50%        0.015927
75%        0.043956
max        1.000000
Name: fare_per_person_minmax, dtype: float64

Describe of fare_per_person_std: count    8.890000e+02
mean     5.994455e-18
std      1.000563e+00
min     -5.533578e-01
25%     -3.505470e-01
50%     -3.250908e-01
75%      7.661451e-02
max      1.377851e+01
Name: fare_per_person_std, dtype: float64

In [ ]:
# Qaysi usulda min 0 ga teng?
# MinMax usulda
# Qaysi usulda max 1 ga teng?
# MinMax usulda
# Qaysi usulda mean 0 atrofida?
# MinMax usulda
# Qaysi usulda std 1 atrofida?
# StandardScaler da

🔥 Task 17 — Outlierni esla

In [ ]:
# Fare'da outlier bo‘lsa, Min-Maxmi yoki Standard Scalingmi ko‘proq mos bo‘lishi mumkin?
#Javob: StandardScaler yaxshi chunki MinMax Scaler da qiymatlar 0 va 1 orasiga zichlashtiriladi fare da outlier qanchalik katta bo'lsa shuncha boshqa normal qiymatlar ham kichiklashib ketadi, chunki minmax outliers ga sezuvchan, standard scaler da esa limit qoyilmagan sigmalar dan foydalanib hisoblanadi, xuddi z_score formulasiga oxshab

In [83]:
for column in df.columns:
  print(column)

PassengerId
Survived
Pclass
Name
Sex
Age
SibSp
Parch
Ticket
Fare
Embarked
family_size
is_alone
Title
fare_per_person
age_group
length_name
sex_encoded
is_alone_encoded
Embarked_C
Embarked_Q
Embarked_S
age_group_adult
age_group_child
age_group_senior
Title_Dr
Title_Master
Title_Miss
Title_Mr
Title_Mrs
Title_Rare
Title_Rev
age_scaled
Fare_scaled
fare_per_person_minmax
fare_per_person_std
family_size_scaled
length_name_std

In [ ]:
#I think now dataset is ready to read our Model

In [86]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked', 'family_size', 'is_alone',
       'Title', 'fare_per_person', 'age_group', 'length_name', 'sex_encoded',
       'is_alone_encoded', 'Embarked_C', 'Embarked_Q', 'Embarked_S',
       'age_group_adult', 'age_group_child', 'age_group_senior', 'Title_Dr',
       'Title_Master', 'Title_Miss', 'Title_Mr', 'Title_Mrs', 'Title_Rare',
       'Title_Rev', 'age_scaled', 'Fare_scaled', 'fare_per_person_minmax',
       'fare_per_person_std', 'family_size_scaled', 'length_name_std'],
      dtype='object')

In [ ]:
X = df[['Pclass', 'sex_encoded', 'is_alone_encoded', 'Embarked_C','Embarked_Q', 'Embarked_S',
       'age_group_adult', 'age_group_child', 'age_group_senior', 'Title_Dr',
       'Title_Master', 'Title_Miss', 'Title_Mr', 'Title_Mrs', 'Title_Rare',
       'Title_Rev', 'age_scaled', 'Fare_scaled',
       'fare_per_person_std', 'family_size_scaled', 'length_name_std']]
y = df['Survived']

In [90]:
df.groupby('Sex')['sex_encoded'].mean()

Sex
female    0.0
male      1.0
Name: sex_encoded, dtype: float64